# Generated by Django 3.1 on 2020-09-05 14:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Privacy',
            fields=[
                ('privacy_id', models.AutoField(primary_key=True, serialize=False)),
                ('privacy_status', models.CharField(blank=True, max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='privacy_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='user.privacy'),
        ),
    ]
