# Generated by Django 3.1 on 2020-09-06 10:44

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0002_auto_20200905_2029'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mood',
            fields=[
                ('mood_id', models.AutoField(primary_key=True, serialize=False)),
                ('mood_type', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('post_id', models.AutoField(primary_key=True, serialize=False)),
                ('post_text', models.TextField(blank=True)),
                ('last_modified_by', models.IntegerField()),
                ('last_modified_date', models.DateField(default=datetime.datetime.now)),
                ('mood_id', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='post.mood')),
                ('user_id', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='user.user')),
            ],
        ),
    ]
